### ISSUE TITLE
Python 3.10’s structural pattern matching

### ISSUE THREAD

**Issue by cclauss** [richardolsson/falcon-routing-survey#1]
Could Python 3.10’s structural pattern matching be used to make routers faster?

**Comment by richardolsson** [comment]
Perhaps, but I'm not sure how that would work. More importantly though, this survey is now 8 years old, and at the time the compiled router was the fastest option, and ended up being implemented in Falcon.

I'm not sure what has happened to routing in Falcon since, but if you have suggestions on how to improve it further, the [falcon repo](https://github.com/falconry/falcon) is a better place to suggest it.

Thanks for contributing!
